Minor tweaks to the readme
danielzfranklin/cargo-rr pull request #7
Opened 2021-05-06 15:08 UTC by grunweg

While writing some installation instructions, two minor changes to the readme felt appropriate. Feel free to accept or decline those as you prefer!

2021-05-06 15:09 UTC, grunweg commented
And here are some installation instructions. (I would like to include them in a second commit, but don't want to fiddle with github's UI too much right now.)

## Installation

`cargo-rr` is a [custom cargo command](https://doc.rust-lang.org/stable/book/ch14-05-extending-cargo.html). It can be installed by installing the `cargo-rr` package from `crates.io`: just run
`cargo install cargo-rr` in a terminal.
This will download the source code for cargo-rr and all its dependencies and compile the package from source.

Upon success, you can run `cargo rr` in the terminal to access `cargo-rr`.
Usually, you want to run onen of `cargo-rr`'s subcommands (such as `test` for recording the execution of a test, `run` for recording the execution of a binary or `replay` to replay an ``rr`` trace you recorded using one of the previous commands).
Running `cargo rr help` or just `cargo rr` will display a list of all available subcommands.

XXX what's the minimum required rust version

2021-05-06 15:14 UTC, danielzfranklin commented
Thanks! I've been meaning to write something like that for a while. I like your phrasing.

I'll probably hold off on publishing an update until I've finished the changes I'm working on around better supporting tests in main.

2021-05-06 15:24 UTC, grunweg commented
Sure, I don't think this is very urgent.
About the rust version: I successfully installed cargo-rr using the 2021-04-24 nightly; 1.51.0 stable also works. (Those were the toolchains I had lying around.) I'll leave further fun to you :-) I know Debian includes rustc 1.34 (on armel) resp. 1.41.0 (everywhere else); those might be interesting to test.

2021-05-06 15:43 UTC, danielzfranklin requested changes
Overall, I like this. I've made a few minor nitpicky changes, and expanded the usage section to include some things I'd meant to explain.

2021-05-06 15:43 UTC, danielzfranklin commented on README.md
> +## Example demonstration
```suggestion
## Example
```

2021-05-06 15:43 UTC, danielzfranklin commented on README.md
> +`cargo-rr` is a [custom cargo command](custom-cargo-commands). It can be installed
```suggestion
`cargo-rr` is a [custom cargo subcommand](custom-cargo-subcommands). It can be installed
```

2021-05-06 15:43 UTC, danielzfranklin commented on README.md
> +[custom-cargo-commands]: https://doc.rust-lang.org/stable/book/ch14-05-extending-cargo.html
```suggestion
[custom-cargo-subcommands]: https://doc.rust-lang.org/stable/book/ch14-05-extending-cargo.html
```

2021-05-06 15:43 UTC, danielzfranklin commented on README.md
> +Upon success, you can run `cargo rr` in the terminal to access `cargo-rr`.
```suggestion
in a terminal. After installing you can run `cargo rr` in the terminal to access `cargo-rr`.
```

2021-05-06 15:43 UTC, danielzfranklin commented on README.md
> +
I'd like to expand this into its own section.

```suggestion
## Usage

Run `cargo rr test` or `cargo rr run` with any options you'd normally give to `cargo test` or `cargo run`. For example, you might run `cargo rr test --test my_integration_test some_filter`.

Once you've made a recording you can replay the last recording in a debugger with `cargo rr replay`.

### Advanced

You can pass options to rr by putting them after the separater `--`. If you do so, you are responsible for making sure the options you set don't conflict with the options `cargo-rr` sets for you. In general, you should be fine if you avoid customizing where traces go or what they're named. Please file a bug if you run into a conflict so I can add the option you want to `cargo-rr`.

`cargo rr test` and `cargo rr run` call `rr record` under the hood, so you can see the full list of rr options by running `rr record -h`. For example, `cargo rr test --test my_test -- --chaos` runs the tests under chaos mode, which randomizes scheduling decisions to try to surface concurrency bugs.

`cargo rr replay` calls `rr replay` under the hood, so you can see the full list of rr options by running `rr replay -h`. For example, `rr replay -- --stats=10000` displays brief stats every 10,000 steps.

Run `cargo rr help` to see the full usage.
```

2021-05-07 10:11 UTC, grunweg commented
Thanks for the feedback! I like those suggestions and just added them.

One more idea: as I understand it, `cargo-rr` passes the `rust-gdb` script to rr automatically (via the `--debugger` option). I was looking for that a bit today; mentioning this could also help :-) Perhaps like the following:

> `cargo-rr` configures `rr` to use the rust pretty-printer for `gdb` (by passing the `-d rust-gdb` option to `rr`).

2021-05-07 12:33 UTC, danielzfranklin commented
> cargo-rr configures rr to use the rust pretty-printer for gdb (by passing the -d rust-gdb option to rr).

I like it. How do you think about putting it in the advanced section, and phrasing it something like

> cargo-rr configures rr to use the rust pretty-printer for gdb, so you don't need to (by passing the -d rust-gdb option to rr).

2021-05-07 13:33 UTC, grunweg commented
Sounds good to me! Feel free to add this to this branch directly.

2022-01-19 21:20 UTC, merged